/*CREATE DATABASE EMPRESA;*/

USE EMPRESA;
/*
CREATE TABLE DEPARTAMENTO(
	Dnome VARCHAR(30) NOT NULL,
    Dnumero INT NOT NULL,
    Cpf_gerente INT NOT NULL,
    Data_nicio_gerente DATE NOT NULL,
    PRIMARY KEY(Dnumero),
    UNIQUE(Cpf_gerente)
);
*/
/*
CREATE TABLE LOCALIZACAO_DEP(
	Dnumero INT NOT NULL,
    Dlocal VARCHAR(30) NOT NULL,
    primary key(Dlocal),
	FOREIGN KEY(Dnumero) REFERENCES DEPARTAMENTO(Dnumero)
    
);
*/
/*
CREATE TABLE FUNCIONARIO(
	Pnome VARCHAR(30) NOT NULL,
    Minicial CHAR NOT NULL,
    Unome VARCHAR(30) NOT NULL,
    Cpf INT NOT NULL,
    Datanasc DATE NOT NULL,
    Endereco VARCHAR(30) NOT NULL,
    Sexo CHAR NOT NULL,
    Salario DOUBLE NOT NULL,
    Cpf_surpevisor INT,
    Dnr INT NOT NULL,
    PRIMARY KEY(Cpf),
    FOREIGN KEY(Cpf_surpevisor) REFERENCES DEPARTAMENTO(Cpf_gerente)
);
*/

/*
CREATE TABLE PROJETO(
	Projnome VARCHAR(30) NOT NULL,
    Projnumero INT NOT NULL,
    Projlocal VARCHAR(30) NOT NULL,
    Dnum INT NOT NULL,
    PRIMARY KEY(Projnumero),
    FOREIGN KEY(Projlocal) REFERENCES LOCALIZACAO_DEP(Dlocal),
    FOREIGN KEY(Dnum) REFERENCES DEPARTAMENTO(Dnumero)
);
*/

/*
CREATE TABLE TRABALHA_EM(
	Fcpf INT NOT NULL,
    Pnr INT NOT NULL,
    Horas FLOAT,
    FOREIGN KEY(Fcpf) REFERENCES FUNCIONARIO(Cpf),
    FOREIGN KEY(Pnr) REFERENCES PROJETO(Projnumero)
);
*/

CREATE TABLE DEPENDENTE(
	Fcpf INT NOT NULL,
    Nome_dependente VARCHAR(30) NOT NULL,
    Sexo CHAR NOT NULL,
    Datanasc DATE NOT NULL,
    Parentesco VARCHAR(30) NOT NULL,
    PRIMARY KEY(Nome_dependente),
    FOREIGN KEY(Fcpf) REFERENCES FUNCIONARIO(Cpf)
);



